[package]
name = "reedfrost"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib creates a dynamic system library
# rlib allows for testing with `wasm-pack test`
crate-type = ["cdylib", "rlib"]

[dependencies]
assert_approx_eq = "1.1.0"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.

console_error_panic_hook = { version = "0.1.7", optional = true }
probability = "0.20.3"
wasm-bindgen = "0.2.100"

[dev-dependencies]
wasm-bindgen-test = "0.3.50"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[features]
console_error_panic_hook = ["dep:console_error_panic_hook"]
