name: Setup Frontend Environment
description: Sets up Node.js, pnpm, and installs frontend dependencies
runs:
  using: composite
  steps:
    - run: |
        npm install --global corepack@latest
        corepack enable
        corepack prepare pnpm@latest-10 --activate
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "pnpm"

    - run: pnpm install
      shell: bash
