name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install frontend dependencies
        uses: ./.github/actions/frontend-setup
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: ./.github/actions/pre-commit
